version: 2
jobs:
  run_tests:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-apt-{{ checksum "setup.py" }}

      - restore_cache:
          key: v1-py3-venv-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Install HDF5
          command: |
            apt-get update
            apt-get -y install libhdf5-serial-dev

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca-france-data
            python -m venv /tmp/venv/openfisca-france-data
            echo "source /tmp/venv/openfisca-france-data/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: make install

      - save_cache:
          key: v1-py3-venv-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca-france-data

      - save_cache:
          key: v1-py3-apt-{{ checksum "setup.py" }}
          paths:
            - /var/cache/apt/archives

      - run:
          name: Run tests
          command: |
            make test
            coveralls

  check_version:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            .circleci/is-version-number-acceptable.sh

  deploy:
      docker:
        - image: python:3.7

      steps:
        - checkout

        - run:
            name: Check for functional changes
            command: if ! .circleci/has-functional-changes.sh ; then circleci step halt ; fi

        - run:
            name: Publish a git tag
            command: .circleci/publish-git-tag.sh

workflows:
  version: 2
  build:
    jobs:
      - run_tests
      - check_version
      - deploy:
          requires:
            # TODO: comment out once tests pass
            # - run_tests
            - check_version
          filters:
            branches:
              # TODO: change once release/1.0.0 is integrated in master
              # only: master
              only: release/1.0.0

